displayName=Choice Man
author=ChunkyAtlas
description=Every level increase grants a choice of one unlock from a set of items. \
   Credit to https://www.youtube.com/@QueueScape
tags=level,unlock,progression,ironman,grand exchange,collection log
plugins=com.choiceman.ChoiceManPlugin
build=standard